version: "3.7"
services:
    mysqldb:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "testuser"
            MYSQL_USER: "testuser"
            MYSQL_PASSWORD: "304testpw"
            MYSQL_ROOT_PASSWORD: "304rootpw"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - cosc304-db:/var/lib/mysql
            - ./ddl:/docker-entrypoint-initdb.d
    node:
        depends_on:
            - mysqldb
        build:
            context: ./
            dockerfile: Dockerfile
        image: node-app
        container_name: node-app
        volumes:
            - ./:/app/
            - /app/node_modules
        networks:
            node-network:
                aliases:
                    - node-app
        ports:
            - 80:3000
        tty: true
volumes:
    cosc304-db:
networks:
    node-network:
